"""
FHSS Simulation v3 — Live FFT + Waterfall + Modulation Selector + Demodulation Console
========================================================================================
Requires: PyQt5, matplotlib, numpy, scipy
Install:  pip install PyQt5 matplotlib numpy scipy
Run:      python fhss_simulation_v3.py
"""

import sys
import numpy as np
import random
from collections import deque
from datetime import datetime

from PyQt5.QtWidgets import (
    QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
    QPushButton, QLabel, QSpinBox, QDoubleSpinBox, QGroupBox,
    QTableWidget, QTableWidgetItem, QHeaderView, QSlider, QComboBox,
    QSplitter, QFrame, QTabWidget, QScrollArea, QTextEdit, QCheckBox
)
from PyQt5.QtCore import Qt, QTimer, pyqtSignal
from PyQt5.QtGui import QFont, QColor, QPalette, QTextCursor

import matplotlib
matplotlib.use('Qt5Agg')
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
import matplotlib.patches as mpatches
import matplotlib.gridspec as gridspec
from matplotlib.colors import LinearSegmentedColormap

# ─────────────────────────────────────────────────────────────────────────────
# Palette
# ─────────────────────────────────────────────────────────────────────────────
BG      = "#0d1117"
PANEL   = "#161b22"
BORDER  = "#30363d"
ACCENT  = "#00d4ff"
ACCENT2 = "#ff6b35"
GREEN   = "#39d353"
YELLOW  = "#e3b341"
MUTED   = "#8b949e"
TEXT    = "#e6edf3"
HOVER   = "#1f2937"
RED     = "#f85149"

CHANNEL_COLORS = [
    "#00d4ff","#ff6b35","#39d353","#f0e68c",
    "#da70d6","#87ceeb","#ff69b4","#98fb98",
    "#ffa500","#7b68ee","#20b2aa","#ff4500",
    "#9370db","#3cb371","#b8860b","#4682b4",
]

_wf_cmap = LinearSegmentedColormap.from_list(
    "waterfall",
    [(0,"#000000"),(0.25,"#0a2a6e"),(0.5,"#00d4ff"),
     (0.75,"#ffaa00"),(1.0,"#ffffff")]
)

# ─────────────────────────────────────────────────────────────────────────────
# Demodulator — extracts real decisions from IQ samples
# ─────────────────────────────────────────────────────────────────────────────
class Demodulator:
    """
    Performs actual demodulation on complex IQ samples generated by ModulationEngine.
    Returns structured DemodResult with real symbol/bit decisions and measured metrics.
    """

    @staticmethod
    def measure_snr(iq: np.ndarray) -> float:
        """
        Estimate SNR from IQ samples using moment-based method.
        Assumes signal has been normalized to unit power.
        SNR_est = E[|x|^2]^2 / Var(|x|^2)  (4th-order moment estimator)
        """
        mag2 = np.abs(iq) ** 2
        mu   = np.mean(mag2)
        var  = np.var(mag2)
        if var < 1e-12:
            return 40.0
        snr_lin = mu**2 / (var + 1e-12)
        return float(np.clip(10 * np.log10(snr_lin + 1e-12), -10, 50))

    @staticmethod
    def measure_evm(iq: np.ndarray, mod: str) -> float:
        """
        Error Vector Magnitude — difference between received symbols and ideal constellation.
        Returns EVM in percent.
        """
        ideal = Demodulator._get_ideal_constellation(iq, mod)
        if ideal is None or len(ideal) == 0:
            return 0.0
        errors = iq - ideal
        signal_power = np.mean(np.abs(ideal) ** 2) + 1e-12
        error_power  = np.mean(np.abs(errors) ** 2)
        evm_pct = 100.0 * np.sqrt(error_power / signal_power)
        return float(np.clip(evm_pct, 0, 100))

    @staticmethod
    def _get_ideal_constellation(iq: np.ndarray, mod: str) -> np.ndarray:
        """Map each IQ sample to its nearest ideal constellation point."""
        if mod == "BPSK":
            pts = np.array([1+0j, -1+0j])
        elif mod == "QPSK":
            pts = np.exp(1j * np.array([0.25, 0.75, 1.25, 1.75]) * np.pi)
        elif mod == "8PSK":
            pts = np.exp(1j * 2 * np.pi * np.arange(8) / 8)
        elif mod == "16QAM":
            r   = np.array([-3, -1, 1, 3]) / 3.0
            pts = np.array([a + 1j*b for a in r for b in r])
        elif mod == "64QAM":
            r   = (np.arange(8) * 2 - 7) / 7.0
            pts = np.array([a + 1j*b for a in r for b in r])
        else:
            return None

        # Find closest constellation point for each sample
        iq_flat = iq.flatten()[:min(len(iq), 512)]
        dists   = np.abs(iq_flat[:, None] - pts[None, :])
        nearest = pts[np.argmin(dists, axis=1)]
        return nearest

    @staticmethod
    def demodulate_psk(iq: np.ndarray, M: int) -> dict:
        """Decision-directed PSK demodulation. Returns symbol indices and bit string."""
        phases = np.angle(iq)
        # Normalize phases to [0, 2π)
        phases = phases % (2 * np.pi)
        sym_indices = np.round(phases / (2 * np.pi / M)).astype(int) % M

        k    = int(np.log2(M))
        bits = []
        for idx in sym_indices:
            # Gray code decode
            gray_idx = idx ^ (idx >> 1)
            bits.extend([(gray_idx >> (k - 1 - b)) & 1 for b in range(k)])

        return {
            "symbols": sym_indices[:16].tolist(),
            "bits":    bits[:64],
            "k_bps":   k,
        }

    @staticmethod
    def demodulate_qam(iq: np.ndarray, M: int) -> dict:
        """Decision-directed QAM demodulation."""
        sqM    = int(np.sqrt(M))
        levels = np.linspace(-(sqM - 1), sqM - 1, sqM) / (sqM - 1)
        k      = int(np.log2(M))

        I_dec = np.array([levels[np.argmin(np.abs(levels - s.real))] for s in iq])
        Q_dec = np.array([levels[np.argmin(np.abs(levels - s.imag))] for s in iq])

        I_idx = np.array([np.argmin(np.abs(levels - s.real)) for s in iq])
        Q_idx = np.array([np.argmin(np.abs(levels - s.imag)) for s in iq])
        sym_indices = I_idx * sqM + Q_idx

        bits = []
        for idx in sym_indices[:32]:
            for b in range(k):
                bits.append((idx >> (k - 1 - b)) & 1)

        return {
            "symbols":   sym_indices[:16].tolist(),
            "I_levels":  I_dec[:8].tolist(),
            "Q_levels":  Q_dec[:8].tolist(),
            "bits":      bits[:64],
            "k_bps":     k,
        }

    @staticmethod
    def demodulate_fsk(iq: np.ndarray, fs: float = 1.0) -> dict:
        """Non-coherent FSK: instantaneous frequency deviation → bit decisions."""
        phase = np.unwrap(np.angle(iq))
        inst_freq = np.diff(phase) / (2 * np.pi)          # normalized frequency
        bits = (inst_freq > 0).astype(int)

        # Measure deviation
        f0 = float(np.mean(inst_freq[bits == 0]))
        f1 = float(np.mean(inst_freq[bits == 1]))
        deviation = abs(f1 - f0)

        return {
            "bits":           bits[:64].tolist(),
            "freq_deviation": deviation,
            "f0_norm":        round(f0, 4),
            "f1_norm":        round(f1, 4),
        }

    @staticmethod
    def demodulate_msk_gmsk(iq: np.ndarray) -> dict:
        """Differential phase demodulation for MSK/GMSK (h=0.5)."""
        phase = np.unwrap(np.angle(iq))
        diff_phase = np.diff(phase)
        bits = (diff_phase > 0).astype(int)
        avg_step = float(np.mean(np.abs(diff_phase)))
        return {
            "bits":      bits[:64].tolist(),
            "avg_phase_step_rad": round(avg_step, 4),
            "h_measured": round(avg_step / np.pi, 4),
        }

    @staticmethod
    def demodulate_fm(iq: np.ndarray) -> dict:
        """FM discriminator: instantaneous frequency → audio samples."""
        phase    = np.unwrap(np.angle(iq))
        audio    = np.diff(phase)                          # discriminator output
        peak_dev = float(np.max(np.abs(audio)))
        thd      = Demodulator._thd(audio)
        return {
            "audio_samples":  [round(float(a), 4) for a in audio[:16]],
            "peak_deviation": round(peak_dev, 4),
            "thd_pct":        round(thd, 2),
        }

    @staticmethod
    def demodulate_am(iq: np.ndarray) -> dict:
        """AM envelope detection."""
        envelope    = np.abs(iq)
        dc          = float(np.mean(envelope))
        ac          = envelope - dc
        mod_index   = float(np.max(np.abs(ac)) / (dc + 1e-12))
        return {
            "dc_level":         round(dc, 4),
            "modulation_index": round(mod_index, 4),
            "peak_envelope":    round(float(np.max(envelope)), 4),
        }

    @staticmethod
    def demodulate_ofdm(iq: np.ndarray, n_sc: int = 64) -> dict:
        """OFDM: FFT per block, measure subcarrier powers."""
        blocks = []
        for start in range(0, len(iq) - n_sc, n_sc):
            block = iq[start:start + n_sc]
            blocks.append(np.fft.fft(block))
        if not blocks:
            return {"subcarrier_powers_db": [], "active_subcarriers": 0}

        sc_pwr = np.mean([np.abs(b)**2 for b in blocks], axis=0)
        threshold = np.max(sc_pwr) * 0.1
        active    = int(np.sum(sc_pwr > threshold))
        pwr_db    = [round(float(10 * np.log10(p + 1e-12)), 1) for p in sc_pwr[:16]]
        return {
            "subcarrier_powers_db": pwr_db,
            "active_subcarriers":   active,
            "n_fft":                n_sc,
        }

    @staticmethod
    def demodulate_css(iq: np.ndarray) -> dict:
        """LoRa-like CSS: dechirp and FFT to find symbol frequency bin."""
        n = len(iq)
        t = np.arange(n)
        # Reference down-chirp
        ref_chirp = np.exp(-1j * np.pi * 0.5 * (t / n) ** 2 * n)
        dechirped  = iq * ref_chirp
        spectrum   = np.abs(np.fft.fft(dechirped))
        peak_bin   = int(np.argmax(spectrum))
        peak_pwr   = float(np.max(spectrum))
        noise_floor = float(np.mean(spectrum)) + 1e-12
        sir         = round(20 * np.log10(peak_pwr / noise_floor), 1)
        return {
            "peak_bin":  peak_bin,
            "sir_db":    sir,
            "spreading_factor_est": round(np.log2(n), 1),
        }

    @staticmethod
    def demodulate_dsss(iq: np.ndarray, chip_rate: int = 11) -> dict:
        """DSSS: despread with reference PN, extract data bits."""
        rng     = np.random.default_rng(42)            # same seed used in ModulationEngine
        chips   = rng.integers(0, 2, len(iq)) * 2 - 1
        despread = (iq.real * chips)                    # correlate with PN
        n_bits  = len(iq) // chip_rate
        bits    = []
        for i in range(n_bits):
            segment = despread[i * chip_rate:(i + 1) * chip_rate]
            bits.append(1 if np.sum(segment) > 0 else 0)
        corr_gain = round(10 * np.log10(chip_rate), 1)
        return {
            "bits":              bits[:32],
            "chip_rate":         chip_rate,
            "processing_gain_db": corr_gain,
        }

    @staticmethod
    def demodulate_cw(iq: np.ndarray) -> dict:
        """CW: envelope thresholding → Morse dit/dah classification."""
        envelope  = np.abs(iq)
        threshold = (np.max(envelope) + np.min(envelope)) / 2
        key       = (envelope > threshold).astype(int)
        # Find runs
        runs = []
        current = key[0]
        count   = 1
        for v in key[1:]:
            if v == current:
                count += 1
            else:
                runs.append((int(current), count))
                current = v
                count   = 1
        runs.append((int(current), count))
        avg_on = float(np.mean([r[1] for r in runs if r[0] == 1])) if any(r[0] == 1 for r in runs) else 0
        elements = []
        for v, c in runs[:10]:
            if v == 1:
                elements.append("·" if c < avg_on * 1.5 else "—")
            else:
                elements.append("_")
        return {
            "elements":  elements,
            "duty_cycle": round(float(np.mean(key)), 3),
            "runs":      len(runs),
        }

    @staticmethod
    def _thd(signal: np.ndarray) -> float:
        """Total Harmonic Distortion estimate (%)."""
        spectrum = np.abs(np.fft.rfft(signal))
        if len(spectrum) < 2 or spectrum[1] < 1e-12:
            return 0.0
        fundamental = spectrum[1]
        harmonics   = np.sqrt(np.sum(spectrum[2:min(10, len(spectrum))]**2))
        return float(100.0 * harmonics / (fundamental + 1e-12))

    @classmethod
    def demodulate(cls, mod: str, iq: np.ndarray, snr_db: float) -> dict:
        """
        Top-level dispatcher. Returns a structured result dict with:
          - mod:         modulation name
          - snr_measured: estimated SNR from IQ samples (dB)
          - evm_pct:     EVM for constellation mods (%)
          - noise_ok:    True if measured SNR is within 3 dB of configured SNR
          - detail:      modulation-specific demod data
          - bits_sample: first 16 bits as hex string (when available)
        """
        # Normalise
        iq = iq / (np.max(np.abs(iq)) + 1e-12)

        snr_meas = cls.measure_snr(iq)
        noise_ok = (snr_meas >= snr_db - 4.0)

        evm = 0.0
        detail = {}

        if mod == "BPSK":
            detail = cls.demodulate_psk(iq, 2)
            evm    = cls.measure_evm(iq, mod)
        elif mod == "QPSK":
            detail = cls.demodulate_psk(iq, 4)
            evm    = cls.measure_evm(iq, mod)
        elif mod == "8PSK":
            detail = cls.demodulate_psk(iq, 8)
            evm    = cls.measure_evm(iq, mod)
        elif mod == "16QAM":
            detail = cls.demodulate_qam(iq, 16)
            evm    = cls.measure_evm(iq, mod)
        elif mod == "64QAM":
            detail = cls.demodulate_qam(iq, 64)
            evm    = cls.measure_evm(iq, mod)
        elif mod in ("RTCM/MSK",):
            detail = cls.demodulate_msk_gmsk(iq)
        elif mod == "GMSK":
            detail = cls.demodulate_msk_gmsk(iq)
        elif mod == "FSK":
            detail = cls.demodulate_fsk(iq)
        elif mod == "AM-DSB":
            detail = cls.demodulate_am(iq)
        elif mod == "FM":
            detail = cls.demodulate_fm(iq)
        elif mod == "OFDM":
            detail = cls.demodulate_ofdm(iq)
        elif mod == "CSS (LoRa-like)":
            detail = cls.demodulate_css(iq)
        elif mod == "DSSS":
            detail = cls.demodulate_dsss(iq)
        elif mod == "CW":
            detail = cls.demodulate_cw(iq)

        # Extract bits sample if present
        raw_bits = detail.get("bits", [])
        bits_hex = ""
        if raw_bits:
            # pack bits into bytes
            padded = raw_bits + [0] * (8 - len(raw_bits) % 8) if len(raw_bits) % 8 else raw_bits
            byte_vals = [
                int("".join(str(b) for b in padded[i:i+8]), 2)
                for i in range(0, min(len(padded), 64), 8)
            ]
            bits_hex = " ".join(f"{b:02X}" for b in byte_vals[:8])

        return {
            "mod":          mod,
            "snr_measured": round(snr_meas, 1),
            "snr_config":   round(snr_db, 1),
            "evm_pct":      round(evm, 1),
            "noise_ok":     noise_ok,
            "detail":       detail,
            "bits_hex":     bits_hex,
        }


# ─────────────────────────────────────────────────────────────────────────────
# Modulation Signal Generators
# ─────────────────────────────────────────────────────────────────────────────
class ModulationEngine:
    MODULATIONS = [
        "BPSK","QPSK","8PSK","16QAM","64QAM",
        "RTCM/MSK","GMSK","FSK","AM-DSB","FM",
        "OFDM","CSS (LoRa-like)","DSSS","CW"
    ]

    @staticmethod
    def generate(mod: str, n_samples: int, fs: float, snr_db: float = 20.0) -> np.ndarray:
        t   = np.arange(n_samples) / fs
        rng = np.random.default_rng()

        noise_power = 10 ** (-snr_db / 10)
        noise = (rng.standard_normal(n_samples) +
                 1j * rng.standard_normal(n_samples)) * np.sqrt(noise_power / 2)

        def psk_symbols(M):
            k    = int(np.log2(M))
            bits = rng.integers(0, 2, n_samples * k)
            idxs = np.packbits(bits.reshape(-1, k), axis=1,
                               bitorder='big').flatten()[:n_samples] % M
            angles = 2 * np.pi * idxs / M
            return np.exp(1j * angles)

        def qam_symbols(M):
            sqM   = int(np.sqrt(M))
            bits  = rng.integers(0, sqM, n_samples)
            bits2 = rng.integers(0, sqM, n_samples)
            levels = np.linspace(-(sqM - 1), sqM - 1, sqM)
            s = (levels[bits] + 1j * levels[bits2])
            return s / np.max(np.abs(s))

        if mod == "BPSK":
            sym = psk_symbols(2)
            sig = np.repeat(sym, max(1, n_samples // len(sym)))[:n_samples]
        elif mod == "QPSK":
            sym = psk_symbols(4)
            sig = np.repeat(sym, max(1, n_samples // len(sym)))[:n_samples]
        elif mod == "8PSK":
            sym = psk_symbols(8)
            sig = np.repeat(sym, max(1, n_samples // len(sym)))[:n_samples]
        elif mod == "16QAM":
            sym = qam_symbols(16)
            sig = np.repeat(sym, max(1, n_samples // len(sym)))[:n_samples]
        elif mod == "64QAM":
            sym = qam_symbols(64)
            sig = np.repeat(sym, max(1, n_samples // len(sym)))[:n_samples]
        elif mod == "RTCM/MSK":
            bits  = rng.integers(0, 2, n_samples) * 2 - 1
            phase = np.cumsum(bits * np.pi / (2 * max(1, n_samples // 256)))
            sig   = np.exp(1j * phase)
        elif mod == "GMSK":
            from scipy.ndimage import gaussian_filter1d
            bits  = (rng.integers(0, 2, n_samples) * 2 - 1).astype(float)
            bits  = gaussian_filter1d(bits, sigma=max(1, n_samples // 512))
            phase = np.cumsum(bits * np.pi / (2 * max(1, n_samples // 256)))
            sig   = np.exp(1j * phase)
        elif mod == "FSK":
            bits  = rng.integers(0, 2, n_samples)
            dev   = 0.25
            phase = np.cumsum((bits * 2 - 1) * 2 * np.pi * dev / fs * fs / n_samples * n_samples)
            sig   = np.exp(1j * phase / n_samples * 2 * np.pi)
        elif mod == "AM-DSB":
            msg = np.sin(2 * np.pi * 0.02 * np.arange(n_samples))
            sig = (1 + 0.8 * msg).astype(complex)
        elif mod == "FM":
            msg   = np.sin(2 * np.pi * 0.015 * np.arange(n_samples))
            phase = np.cumsum(msg) * 0.3
            sig   = np.exp(1j * phase)
        elif mod == "OFDM":
            n_sc = 64
            sym  = np.zeros(n_samples, dtype=complex)
            block = n_sc
            for start in range(0, n_samples - block, block):
                pilots = np.exp(1j * np.random.uniform(0, 2*np.pi, n_sc))
                sym[start:start+block] = np.fft.ifft(pilots)
            sig = sym
        elif mod == "CSS (LoRa-like)":
            bw  = 0.5
            sig = np.exp(1j * np.pi * bw * (np.arange(n_samples) / n_samples) ** 2 * n_samples)
        elif mod == "DSSS":
            data   = rng.integers(0, 2, n_samples // 11 + 1)
            chip   = rng.integers(0, 2, n_samples)
            spread = (np.repeat(data, 11)[:n_samples] ^ chip) * 2 - 1
            sig    = spread.astype(complex)
        elif mod == "CW":
            key = np.zeros(n_samples)
            for i in range(0, n_samples, n_samples // 8):
                key[i:i + n_samples // 16] = 1
            sig = key.astype(complex)
        else:
            sig = np.ones(n_samples, dtype=complex)

        sig = sig / (np.max(np.abs(sig)) + 1e-12)
        return sig + noise

    @staticmethod
    def spectral_shape(mod: str, freqs_norm: np.ndarray) -> np.ndarray:
        f = freqs_norm
        if mod in ("BPSK",):
            return np.sinc(f * 10) ** 2
        elif mod in ("QPSK", "8PSK"):
            return np.sinc(f * 20) ** 2
        elif mod in ("16QAM", "64QAM"):
            bw = 0.25
            return np.where(np.abs(f) < bw, 1.0,
                   np.where(np.abs(f) < bw * 1.5,
                            0.5 * (1 + np.cos(np.pi * (np.abs(f) - bw) / (0.5 * bw))),
                            0.0))
        elif mod in ("RTCM/MSK", "GMSK"):
            s = 0.5 * np.sinc((f - 0.25) * 8)**2 + 0.5 * np.sinc((f + 0.25) * 8)**2
            return s / (s.max() + 1e-12)
        elif mod == "FSK":
            s = 0.5 * np.exp(-((f-0.15)**2)/(2*0.04**2)) + 0.5 * np.exp(-((f+0.15)**2)/(2*0.04**2))
            return s / s.max()
        elif mod == "AM-DSB":
            s = 0.6*np.exp(-(f**2)/(2*0.01**2)) + 0.2*np.exp(-((f-0.05)**2)/(2*0.01**2)) + 0.2*np.exp(-((f+0.05)**2)/(2*0.01**2))
            return s / s.max()
        elif mod == "FM":
            bw = 0.2
            return np.where(np.abs(f) < bw, 1.0, np.exp(-((np.abs(f)-bw)**2)/(2*0.02**2)))
        elif mod == "OFDM":
            bw = 0.35
            return np.where(np.abs(f) < bw, 1.0, np.exp(-((np.abs(f)-bw)**2)/(2*0.015**2)))
        elif mod == "CSS (LoRa-like)":
            return np.where(np.abs(f) < 0.45, 1.0, 0.0).astype(float)
        elif mod == "DSSS":
            return np.where(np.abs(f) < 0.48, 0.9 + 0.1*np.random.rand(len(f)), 0.0)
        elif mod == "CW":
            return np.exp(-(f**2)/(2*0.005**2))
        else:
            return np.ones_like(f)


# ─────────────────────────────────────────────────────────────────────────────
# FHSS Engine
# ─────────────────────────────────────────────────────────────────────────────
class FHSSEngine:
    def __init__(self):
        self.num_channels  = 8
        self.base_freq     = 2400.0
        self.channel_bw    = 1.0
        self.hop_interval  = 10
        self.sequence_len  = 32
        self.seed          = 42
        self.pattern       = "Pseudo-Random"
        self.modulation    = "QPSK"
        self.snr_db        = 20.0
        self._build_channels()
        self._build_sequence()

    def _build_channels(self):
        self.channels = [
            {"id": i, "freq": round(self.base_freq + i * self.channel_bw, 2),
             "label": f"CH{i+1}", "color": CHANNEL_COLORS[i % len(CHANNEL_COLORS)]}
            for i in range(self.num_channels)
        ]

    def _build_sequence(self):
        rng = random.Random(self.seed)
        if self.pattern == "Pseudo-Random":
            self.sequence = [rng.randint(0, self.num_channels - 1) for _ in range(self.sequence_len)]
        elif self.pattern == "Sequential":
            self.sequence = [i % self.num_channels for i in range(self.sequence_len)]
        elif self.pattern == "Interleaved":
            self.sequence = [
                (i*2) % self.num_channels if i%2==0 else (i*2+1) % self.num_channels
                for i in range(self.sequence_len)
            ]
        else:
            self.sequence = [rng.randint(0, self.num_channels - 1) for _ in range(self.sequence_len)]

    def reconfigure(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)
        self._build_channels()
        self._build_sequence()

    @property
    def time_axis(self):
        return [i * self.hop_interval for i in range(self.sequence_len)]

    @property
    def freq_axis(self):
        return [self.channels[ch]["freq"] for ch in self.sequence]

    @property
    def total_bw(self):
        return self.num_channels * self.channel_bw

    @property
    def span_start(self):
        return self.base_freq - self.channel_bw * 0.5

    @property
    def span_end(self):
        return self.base_freq + self.num_channels * self.channel_bw + self.channel_bw * 0.5


# ─────────────────────────────────────────────────────────────────────────────
# Demodulation Console Widget
# ─────────────────────────────────────────────────────────────────────────────
class DemodConsole(QWidget):
    """
    A live console showing real demodulated data from each hop's IQ samples.
    Data is derived from actual ModulationEngine.generate() output — not mocked.
    """
    MAX_ENTRIES = 200

    def __init__(self, engine: FHSSEngine):
        super().__init__()
        self.engine    = engine
        self.hop_count = 0
        self._paused   = False
        self._setup_ui()

    def _setup_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(4)

        # Toolbar
        toolbar = QWidget()
        tl = QHBoxLayout(toolbar)
        tl.setContentsMargins(0, 0, 0, 0)
        tl.setSpacing(6)

        title = QLabel("Demodulation Console")
        title.setStyleSheet(f"color:{ACCENT}; font-size:11px; font-weight:bold; font-family:'Courier New';")
        tl.addWidget(title)
        tl.addStretch()

        self.cb_verbose = QCheckBox("Verbose")
        self.cb_verbose.setChecked(False)
        self.cb_verbose.setStyleSheet(f"color:{MUTED}; font-size:10px;")
        tl.addWidget(self.cb_verbose)

        self.cb_pause = QCheckBox("Pause")
        self.cb_pause.setChecked(False)
        self.cb_pause.toggled.connect(self._toggle_pause)
        self.cb_pause.setStyleSheet(f"color:{MUTED}; font-size:10px;")
        tl.addWidget(self.cb_pause)

        btn_clear = QPushButton("Clear")
        btn_clear.setFixedWidth(55)
        btn_clear.clicked.connect(self._clear)
        btn_clear.setStyleSheet(f"""
            QPushButton {{ background:{PANEL}; color:{MUTED}; border:1px solid {BORDER};
                border-radius:3px; padding:2px 6px; font-size:9px; }}
            QPushButton:hover {{ color:{TEXT}; }}
        """)
        tl.addWidget(btn_clear)
        layout.addWidget(toolbar)

        # Console text area
        self.console = QTextEdit()
        self.console.setReadOnly(True)
        self.console.setFont(QFont("Courier New", 9))
        self.console.setStyleSheet(f"""
            QTextEdit {{
                background: #080c10;
                color: {TEXT};
                border: 1px solid {BORDER};
                border-radius: 4px;
                padding: 4px;
                selection-background-color: {ACCENT}40;
            }}
        """)
        self.console.setLineWrapMode(QTextEdit.NoWrap)
        layout.addWidget(self.console)

        # Status bar
        self.status_lbl = QLabel("Ready — waiting for first hop")
        self.status_lbl.setStyleSheet(f"color:{MUTED}; font-size:9px; padding:2px 0;")
        layout.addWidget(self.status_lbl)

        # Startup message
        self._print_banner()

    def _print_banner(self):
        self.console.setTextColor(QColor(MUTED))
        self.console.append("┌─────────────────────────────────────────────────────────────────┐")
        self.console.append("│  FHSS Demodulation Console  v3  —  real IQ data, no mocks       │")
        self.console.append("│  Each entry demodulated from ModulationEngine.generate() output  │")
        self.console.append("└─────────────────────────────────────────────────────────────────┘")
        self.console.append("")

    def _toggle_pause(self, paused: bool):
        self._paused = paused

    def _clear(self):
        self.console.clear()
        self.hop_count = 0
        self._print_banner()

    def _color_for_status(self, noise_ok: bool) -> QColor:
        return QColor(GREEN) if noise_ok else QColor(RED)

    def log_hop(self, hop_index: int, ch_index: int, iq_samples: np.ndarray):
        """
        Called on each hop. Demodulates the live IQ samples and logs the results.
        iq_samples are the real output of ModulationEngine.generate().
        """
        if self._paused:
            return

        eng    = self.engine
        ch     = eng.channels[ch_index]
        result = Demodulator.demodulate(eng.modulation, iq_samples, eng.snr_db)
        self.hop_count += 1

        ts      = datetime.now().strftime("%H:%M:%S.%f")[:-3]
        status  = "OK " if result["noise_ok"] else "ERR"
        snr_d   = result["snr_measured"]
        snr_c   = result["snr_config"]
        delta   = round(snr_d - snr_c, 1)
        delta_s = f"+{delta}" if delta >= 0 else str(delta)
        evm     = result["evm_pct"]
        detail  = result["detail"]
        mod     = result["mod"]

        c_ch    = QColor(ch["color"])
        c_ok    = self._color_for_status(result["noise_ok"])
        c_accent = QColor(ACCENT)
        c_muted  = QColor(MUTED)
        c_yellow = QColor(YELLOW)
        c_text   = QColor(TEXT)

        def put(color, text, newline=False):
            self.console.setTextColor(color)
            if newline:
                self.console.append(text)
            else:
                self.console.insertPlainText(text)

        # ── Header line ───────────────────────────────────────────────────────
        self.console.append("")
        self.console.setTextColor(c_muted)
        self.console.insertPlainText(f"[{ts}] ")
        self.console.setTextColor(c_ok)
        self.console.insertPlainText(f"[{status}] ")
        self.console.setTextColor(c_ch)
        self.console.insertPlainText(f"HOP#{hop_index+1:02d} {ch['label']} {ch['freq']:.2f}MHz ")
        self.console.setTextColor(c_accent)
        self.console.insertPlainText(f"{mod} ")
        self.console.setTextColor(c_muted)
        self.console.insertPlainText(f"| SNR={snr_d:+.1f}dB ({delta_s}dB Δ)")
        if evm > 0:
            self.console.setTextColor(c_yellow)
            self.console.insertPlainText(f" EVM={evm:.1f}%")

        # ── Modulation-specific detail ────────────────────────────────────────
        if mod in ("BPSK", "QPSK", "8PSK"):
            syms = detail.get("symbols", [])
            bpsk = detail.get("bits", [])
            bits_hex = result["bits_hex"]
            self.console.append("")
            self.console.setTextColor(c_muted)
            self.console.insertPlainText("  Symbols: ")
            self.console.setTextColor(c_text)
            self.console.insertPlainText(" ".join(str(s) for s in syms[:16]))
            self.console.append("")
            self.console.setTextColor(c_muted)
            self.console.insertPlainText("  Bits:    ")
            self.console.setTextColor(QColor("#4fc3f7"))
            self.console.insertPlainText("".join(str(b) for b in bpsk[:32]))
            if bits_hex:
                self.console.setTextColor(c_muted)
                self.console.insertPlainText(f"  → 0x{bits_hex}")

        elif mod in ("16QAM", "64QAM"):
            syms = detail.get("symbols", [])
            bits_hex = result["bits_hex"]
            self.console.append("")
            self.console.setTextColor(c_muted)
            self.console.insertPlainText("  Symbols: ")
            self.console.setTextColor(c_text)
            self.console.insertPlainText(" ".join(str(s) for s in syms[:12]))
            if self.cb_verbose.isChecked():
                I = detail.get("I_levels", [])
                Q = detail.get("Q_levels", [])
                self.console.append("")
                self.console.setTextColor(c_muted)
                self.console.insertPlainText("  I-lvl:  ")
                self.console.setTextColor(c_text)
                self.console.insertPlainText(" ".join(f"{v:+.2f}" for v in I[:8]))
                self.console.append("")
                self.console.setTextColor(c_muted)
                self.console.insertPlainText("  Q-lvl:  ")
                self.console.setTextColor(c_text)
                self.console.insertPlainText(" ".join(f"{v:+.2f}" for v in Q[:8]))
            if bits_hex:
                self.console.append("")
                self.console.setTextColor(c_muted)
                self.console.insertPlainText(f"  Hex:     0x{bits_hex}")

        elif mod in ("RTCM/MSK", "GMSK"):
            bits = detail.get("bits", [])
            h    = detail.get("h_measured", "?")
            step = detail.get("avg_phase_step_rad", "?")
            self.console.append("")
            self.console.setTextColor(c_muted)
            self.console.insertPlainText(f"  h={h} Δφ={step}rad  bits: ")
            self.console.setTextColor(QColor("#4fc3f7"))
            self.console.insertPlainText("".join(str(b) for b in bits[:32]))

        elif mod == "FSK":
            bits = detail.get("bits", [])
            f0   = detail.get("f0_norm", "?")
            f1   = detail.get("f1_norm", "?")
            dev  = detail.get("freq_deviation", "?")
            self.console.append("")
            self.console.setTextColor(c_muted)
            self.console.insertPlainText(f"  f0={f0:+.4f} f1={f1:+.4f} Δf={dev:.4f}  bits: ")
            self.console.setTextColor(QColor("#4fc3f7"))
            self.console.insertPlainText("".join(str(b) for b in bits[:32]))

        elif mod == "AM-DSB":
            dc  = detail.get("dc_level", "?")
            mi  = detail.get("modulation_index", "?")
            pke = detail.get("peak_envelope", "?")
            self.console.append("")
            self.console.setTextColor(c_muted)
            self.console.insertPlainText(f"  DC={dc:.4f}  Mod.Index={mi:.3f}  PeakEnv={pke:.4f}")

        elif mod == "FM":
            audio = detail.get("audio_samples", [])
            dev   = detail.get("peak_deviation", "?")
            thd   = detail.get("thd_pct", "?")
            self.console.append("")
            self.console.setTextColor(c_muted)
            self.console.insertPlainText(f"  PeakDev={dev:.4f}  THD={thd:.2f}%")
            if self.cb_verbose.isChecked():
                self.console.append("")
                self.console.setTextColor(c_muted)
                self.console.insertPlainText("  Audio:   ")
                self.console.setTextColor(c_text)
                self.console.insertPlainText(" ".join(f"{a:+.3f}" for a in audio[:8]))

        elif mod == "OFDM":
            pwrs   = detail.get("subcarrier_powers_db", [])
            active = detail.get("active_subcarriers", "?")
            nfft   = detail.get("n_fft", "?")
            self.console.append("")
            self.console.setTextColor(c_muted)
            self.console.insertPlainText(f"  Active subcarriers: {active}/{nfft}")
            if self.cb_verbose.isChecked():
                self.console.append("")
                self.console.setTextColor(c_muted)
                self.console.insertPlainText("  SC pwr(dB): ")
                self.console.setTextColor(c_text)
                self.console.insertPlainText(" ".join(str(p) for p in pwrs[:16]))

        elif mod == "CSS (LoRa-like)":
            bin_  = detail.get("peak_bin", "?")
            sir   = detail.get("sir_db", "?")
            sf    = detail.get("spreading_factor_est", "?")
            self.console.append("")
            self.console.setTextColor(c_muted)
            self.console.insertPlainText(f"  Peak bin={bin_}  SIR={sir}dB  SF≈{sf}")

        elif mod == "DSSS":
            bits  = detail.get("bits", [])
            pg    = detail.get("processing_gain_db", "?")
            cr    = detail.get("chip_rate", "?")
            self.console.append("")
            self.console.setTextColor(c_muted)
            self.console.insertPlainText(f"  Chip rate={cr}  Proc.Gain={pg}dB  bits: ")
            self.console.setTextColor(QColor("#4fc3f7"))
            self.console.insertPlainText("".join(str(b) for b in bits[:24]))

        elif mod == "CW":
            elems = detail.get("elements", [])
            duty  = detail.get("duty_cycle", "?")
            runs  = detail.get("runs", "?")
            self.console.append("")
            self.console.setTextColor(c_muted)
            self.console.insertPlainText(f"  Duty={duty:.3f}  Runs={runs}  Morse: ")
            self.console.setTextColor(c_yellow)
            self.console.insertPlainText(" ".join(elems))

        # Scroll to bottom
        sb = self.console.verticalScrollBar()
        sb.setValue(sb.maximum())

        # Trim if too long
        doc = self.console.document()
        if doc.lineCount() > self.MAX_ENTRIES * 8:
            cursor = QTextCursor(doc)
            cursor.movePosition(QTextCursor.Start)
            cursor.movePosition(QTextCursor.Down, QTextCursor.KeepAnchor, 40)
            cursor.removeSelectedText()

        # Update status
        noise_delta_txt = f"SNR Δ={delta_s}dB"
        evm_txt = f"  EVM={evm:.1f}%" if evm > 0 else ""
        status_txt = f"Hop #{self.hop_count}  |  {ch['label']} @ {ch['freq']:.2f} MHz  |  {noise_delta_txt}{evm_txt}  |  {'Signal OK' if result['noise_ok'] else '⚠ Noise degraded'}"
        self.status_lbl.setText(status_txt)
        self.status_lbl.setStyleSheet(
            f"color:{'#39d353' if result['noise_ok'] else '#f85149'}; font-size:9px; padding:2px 0;"
        )


# ─────────────────────────────────────────────────────────────────────────────
# Live FFT + Waterfall Canvas
# ─────────────────────────────────────────────────────────────────────────────
class SpectrumCanvas(FigureCanvas):
    N_FFT       = 512
    WATERFALL_H = 80
    NOISE_FLOOR = -90.0
    PEAK_POWER  = -20.0

    # Signal: emits live IQ samples for the demod console
    iq_generated = pyqtSignal(int, int, object)   # hop_idx, ch_idx, iq_ndarray

    def __init__(self, engine: FHSSEngine, parent=None):
        self.engine      = engine
        self._wf_data    = np.full((self.WATERFALL_H, self.N_FFT), self.NOISE_FLOOR, dtype=float)
        self._peak_hold  = np.full(self.N_FFT, self.NOISE_FLOOR)
        self.fig         = Figure(facecolor=BG)
        super().__init__(self.fig)
        self.setParent(parent)
        self._build_axes()
        self._init_artists()

    def _build_axes(self):
        self.fig.clear()
        gs = gridspec.GridSpec(2, 1, figure=self.fig, height_ratios=[2, 1.2],
                               hspace=0.08, left=0.08, right=0.97, top=0.93, bottom=0.08)
        self.ax_fft = self.fig.add_subplot(gs[0])
        self.ax_wf  = self.fig.add_subplot(gs[1], sharex=self.ax_fft)
        for ax in (self.ax_fft, self.ax_wf):
            ax.set_facecolor(BG)
            ax.tick_params(colors=MUTED, labelsize=7.5)
            for sp in ax.spines.values():
                sp.set_edgecolor(BORDER)
        self.fig.patch.set_facecolor(BG)
        self.ax_fft.set_title("Live Spectrum  +  Waterfall", color=TEXT,
                               fontsize=10, fontweight="bold", pad=6)
        self.ax_fft.set_ylabel("Power (dBm)", color=MUTED, fontsize=8)
        self.ax_fft.set_ylim(self.NOISE_FLOOR, self.PEAK_POWER + 15)
        self.ax_fft.grid(color=BORDER, linewidth=0.4, alpha=0.6)
        self.ax_wf.set_xlabel("Frequency (MHz)", color=MUTED, fontsize=8)
        self.ax_wf.set_ylabel("Time →", color=MUTED, fontsize=7)
        self.ax_fft.tick_params(labelbottom=False)

    def _init_artists(self):
        eng  = self.engine
        freq = self._freq_axis()
        self._fft_line, = self.ax_fft.plot(freq, np.full(self.N_FFT, self.NOISE_FLOOR),
                                            color=ACCENT, linewidth=1.0, alpha=0.9, zorder=5)
        self._peak_line, = self.ax_fft.plot(freq, np.full(self.N_FFT, self.NOISE_FLOOR),
                                             color=ACCENT2, linewidth=0.6, alpha=0.5,
                                             linestyle="--", zorder=4)
        self._band_patches = []
        for ch in eng.channels:
            p = self.ax_fft.axvspan(ch["freq"] - eng.channel_bw*0.5,
                                     ch["freq"] + eng.channel_bw*0.5,
                                     alpha=0.07, color=ch["color"], zorder=1)
            self._band_patches.append(p)
        self._active_span = self.ax_fft.axvspan(
            eng.channels[0]["freq"] - eng.channel_bw*0.5,
            eng.channels[0]["freq"] + eng.channel_bw*0.5,
            alpha=0.25, color=ACCENT, zorder=2)
        self._mod_text = self.ax_fft.text(0.01, 0.95, f"MOD: {eng.modulation}",
            transform=self.ax_fft.transAxes, color=GREEN, fontsize=8,
            fontweight="bold", va="top", fontfamily="monospace")
        self._ch_text = self.ax_fft.text(0.01, 0.86, "CH: —",
            transform=self.ax_fft.transAxes, color=ACCENT, fontsize=8, fontfamily="monospace")
        self._snr_text = self.ax_fft.text(0.01, 0.77, f"SNR: {eng.snr_db:.0f} dB",
            transform=self.ax_fft.transAxes, color=YELLOW, fontsize=8, fontfamily="monospace")
        self._wf_im = self.ax_wf.imshow(self._wf_data, aspect="auto", origin="upper",
            cmap=_wf_cmap, vmin=self.NOISE_FLOOR, vmax=self.PEAK_POWER+10,
            extent=[freq[0], freq[-1], self.WATERFALL_H, 0],
            interpolation="bilinear", zorder=2)
        self._set_xlim()
        self.draw()

    def _freq_axis(self):
        eng = self.engine
        return np.linspace(eng.span_start, eng.span_end, self.N_FFT)

    def _set_xlim(self):
        eng = self.engine
        self.ax_fft.set_xlim(eng.span_start, eng.span_end)
        xticks = [c["freq"] for c in eng.channels]
        self.ax_fft.set_xticks(xticks)
        self.ax_fft.set_xticklabels([f"{x:.1f}" for x in xticks], fontsize=6.5, color=MUTED, rotation=30)

    def _compute_fft_frame(self, ch_idx: int, iq_samples: np.ndarray) -> np.ndarray:
        """
        Build FFT display frame from actual IQ samples.
        Computes real FFT of the IQ, maps it to the display frequency axis.
        """
        eng     = self.engine
        freq    = self._freq_axis()
        ch_freq = eng.channels[ch_idx]["freq"]

        # Compute real FFT power from actual IQ samples
        n     = len(iq_samples)
        win   = np.hanning(n)
        fft   = np.fft.fft(iq_samples * win, n=n)
        psd   = np.abs(np.fft.fftshift(fft)) ** 2
        psd   = psd / (n * np.sum(win**2) + 1e-12)
        psd_db = 10 * np.log10(psd + 1e-12) + self.PEAK_POWER + 15   # shift to dBm range

        # Map IQ FFT bins to display frequency axis
        iq_freqs = np.linspace(ch_freq - eng.channel_bw*0.5,
                               ch_freq + eng.channel_bw*0.5, n)
        # Interpolate IQ FFT onto display freq axis
        frame = np.interp(freq, iq_freqs, psd_db,
                          left=self.NOISE_FLOOR, right=self.NOISE_FLOOR)

        # Add noise floor variation to out-of-channel bins
        noise_mask = (freq < ch_freq - eng.channel_bw*0.55) | (freq > ch_freq + eng.channel_bw*0.55)
        frame[noise_mask] = self.NOISE_FLOOR + np.random.randn(np.sum(noise_mask)) * 1.8

        from scipy.ndimage import uniform_filter1d
        frame = uniform_filter1d(frame, size=3)
        return frame

    def update_hop(self, hop_idx: int):
        if hop_idx < 0:
            return
        eng    = self.engine
        ch_idx = eng.sequence[hop_idx % len(eng.sequence)]
        ch     = eng.channels[ch_idx]
        freq   = self._freq_axis()

        # Generate REAL IQ samples — these power both the FFT display and the demod console
        iq_samples = ModulationEngine.generate(
            eng.modulation, n_samples=512, fs=1.0, snr_db=eng.snr_db
        )

        # Emit IQ to demod console (before FFT processing)
        self.iq_generated.emit(hop_idx, ch_idx, iq_samples)

        # Build FFT frame from real IQ
        frame = self._compute_fft_frame(ch_idx, iq_samples)

        self._peak_hold = np.maximum(self._peak_hold, frame)
        self._peak_hold = self._peak_hold * 0.97 + self.NOISE_FLOOR * 0.03

        self._fft_line.set_ydata(frame)
        self._peak_line.set_ydata(self._peak_hold)

        x0 = ch["freq"] - eng.channel_bw*0.5
        x1 = ch["freq"] + eng.channel_bw*0.5
        self._active_span.remove()
        self._active_span = self.ax_fft.axvspan(x0, x1, alpha=0.25, color=ch["color"], zorder=2)

        self._mod_text.set_text(f"MOD: {eng.modulation}")
        self._ch_text.set_text(f"CH:  {ch['label']}  {ch['freq']:.2f} MHz")
        self._snr_text.set_text(f"SNR: {eng.snr_db:.0f} dB")

        self._wf_data = np.roll(self._wf_data, -1, axis=0)
        self._wf_data[-1, :] = frame
        self._wf_im.set_data(self._wf_data)
        self._wf_im.set_extent([freq[0], freq[-1], self.WATERFALL_H, 0])
        self.draw_idle()

    def rebuild(self):
        self._wf_data   = np.full((self.WATERFALL_H, self.N_FFT), self.NOISE_FLOOR, dtype=float)
        self._peak_hold = np.full(self.N_FFT, self.NOISE_FLOOR)
        self._build_axes()
        self._init_artists()


# ─────────────────────────────────────────────────────────────────────────────
# Hop Map Canvas
# ─────────────────────────────────────────────────────────────────────────────
class HopMapCanvas(FigureCanvas):
    def __init__(self, engine: FHSSEngine, parent=None):
        self.engine = engine
        self.fig    = Figure(facecolor=BG)
        super().__init__(self.fig)
        self.setParent(parent)
        self._highlight_patch = None
        self._draw_static()

    def _draw_static(self):
        self.fig.clear()
        self.ax = self.fig.add_subplot(111)
        ax  = self.ax
        eng = self.engine
        ax.set_facecolor(BG)
        self.fig.patch.set_facecolor(BG)
        times = eng.time_axis
        freqs = eng.freq_axis
        seq   = eng.sequence
        chans = eng.channels
        bw    = eng.channel_bw

        for ch in chans:
            ax.axhspan(ch["freq"] - bw*0.45, ch["freq"] + bw*0.45, alpha=0.06, color=ch["color"])
            ax.axhline(ch["freq"], color=ch["color"], alpha=0.15, linewidth=0.5, linestyle="--")

        for i in range(len(times)):
            ch   = chans[seq[i]]
            rect = mpatches.FancyBboxPatch(
                (times[i], freqs[i] - bw*0.4), eng.hop_interval*0.92, bw*0.8,
                boxstyle="round,pad=0.01", linewidth=1.1,
                edgecolor=ch["color"], facecolor=ch["color"]+"35")
            ax.add_patch(rect)
            ax.text(times[i] + eng.hop_interval*0.46, freqs[i], ch["label"],
                    ha="center", va="center", fontsize=6, color=ch["color"],
                    fontweight="bold", alpha=0.85)

        ax.plot([t + eng.hop_interval*0.46 for t in times], freqs,
                color=ACCENT, linewidth=0.8, alpha=0.3, linestyle=":", zorder=5)

        ax.set_xlim(-eng.hop_interval*0.5, times[-1] + eng.hop_interval*1.5)
        freq_vals = [c["freq"] for c in chans]
        ax.set_ylim(min(freq_vals) - bw, max(freq_vals) + bw)
        ax.set_xlabel("Time (ms)", color=TEXT, fontsize=8, labelpad=6)
        ax.set_ylabel("Frequency (MHz)", color=TEXT, fontsize=8, labelpad=6)
        ax.set_title("Hop Map — Frequency vs Time", color=TEXT, fontsize=10, fontweight="bold", pad=8)
        ax.tick_params(colors=MUTED, labelsize=7.5)
        for sp in ax.spines.values():
            sp.set_edgecolor(BORDER)
        ax.set_yticks([c["freq"] for c in chans])
        ax.set_yticklabels([f"{c['freq']:.1f}" for c in chans], fontsize=7, color=MUTED)
        step = max(1, len(times) // 8)
        ax.set_xticks([times[i] for i in range(0, len(times), step)])
        ax.set_xticklabels([str(times[i]) for i in range(0, len(times), step)], fontsize=7, color=MUTED)
        ax.grid(color=BORDER, linewidth=0.35, alpha=0.5)

        handles = [mpatches.Patch(color=c["color"], label=f"{c['label']} {c['freq']} MHz") for c in chans]
        ax.legend(handles=handles, loc="upper right", fontsize=6.2, ncol=2,
                  framealpha=0.2, facecolor=PANEL, edgecolor=BORDER, labelcolor=TEXT)
        self._highlight_patch = None
        self.fig.tight_layout(pad=1.0)
        self.draw()

    def highlight_hop(self, hop_index: int):
        eng   = self.engine
        bw    = eng.channel_bw
        times = eng.time_axis
        freqs = eng.freq_axis
        if self._highlight_patch:
            try:
                self._highlight_patch.remove()
            except Exception:
                pass
            self._highlight_patch = None
        if 0 <= hop_index < len(times):
            rect = mpatches.FancyBboxPatch(
                (times[hop_index], freqs[hop_index] - bw*0.48),
                eng.hop_interval*0.92, bw*0.96,
                boxstyle="round,pad=0.01", linewidth=2.2,
                edgecolor="#ffffff", facecolor="#ffffff1a", zorder=10)
            self.ax.add_patch(rect)
            self._highlight_patch = rect
        self.draw_idle()


# ─────────────────────────────────────────────────────────────────────────────
# Channel Table
# ─────────────────────────────────────────────────────────────────────────────
class ChannelTable(QTableWidget):
    def __init__(self, engine: FHSSEngine):
        super().__init__()
        self.engine = engine
        self.setColumnCount(3)
        self.setHorizontalHeaderLabels(["Channel", "Freq (MHz)", "Hops"])
        self.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.setEditTriggers(QTableWidget.NoEditTriggers)
        self.setSelectionBehavior(QTableWidget.SelectRows)
        self.setAlternatingRowColors(True)
        self.setStyleSheet(f"""
            QTableWidget {{ background:{PANEL}; color:{TEXT}; border:1px solid {BORDER};
                gridline-color:{BORDER}; font-size:11px; }}
            QTableWidget::item:alternate {{ background:{BG}; }}
            QTableWidget::item:selected  {{ background:{ACCENT}40; color:{TEXT}; }}
            QHeaderView::section {{ background:{BG}; color:{MUTED}; border:none;
                border-bottom:1px solid {BORDER}; padding:5px; font-size:10px; }}
        """)
        self.refresh()

    def refresh(self):
        eng = self.engine
        hop_counts = [0] * eng.num_channels
        for ch in eng.sequence:
            hop_counts[ch] += 1
        self.setRowCount(eng.num_channels)
        for i, ch in enumerate(eng.channels):
            color = QColor(ch["color"])
            lbl   = QTableWidgetItem(ch["label"])
            lbl.setForeground(color)
            lbl.setFont(QFont("Courier New", 10, QFont.Bold))
            freq  = QTableWidgetItem(f"{ch['freq']:.2f}")
            freq.setTextAlignment(Qt.AlignCenter)
            freq.setForeground(QColor(TEXT))
            hops  = QTableWidgetItem(str(hop_counts[i]))
            hops.setTextAlignment(Qt.AlignCenter)
            hops.setForeground(QColor(GREEN if hop_counts[i] > 0 else MUTED))
            self.setItem(i, 0, lbl)
            self.setItem(i, 1, freq)
            self.setItem(i, 2, hops)

    def highlight_channel(self, ch_index: int):
        self.selectRow(ch_index)


# ─────────────────────────────────────────────────────────────────────────────
# Sequence Widget
# ─────────────────────────────────────────────────────────────────────────────
class SequenceWidget(QFrame):
    def __init__(self, engine: FHSSEngine):
        super().__init__()
        self.engine = engine
        self.setFrameShape(QFrame.StyledPanel)
        self.setStyleSheet(f"background:{PANEL}; border:1px solid {BORDER}; border-radius:6px;")
        layout = QVBoxLayout(self)
        layout.setContentsMargins(8, 5, 8, 5)
        layout.setSpacing(3)
        title = QLabel("Hopping Sequence")
        title.setStyleSheet(f"color:{MUTED}; font-size:10px; font-weight:600;")
        layout.addWidget(title)
        self.seq_label = QLabel()
        self.seq_label.setWordWrap(True)
        self.seq_label.setStyleSheet(f"color:{TEXT}; font-family:'Courier New'; font-size:10px;")
        layout.addWidget(self.seq_label)
        self.refresh()

    def refresh(self):
        eng  = self.engine
        html = ""
        for i, ch in enumerate(eng.sequence):
            color = eng.channels[ch]["color"]
            label = eng.channels[ch]["label"]
            html += f'<span style="color:{color};font-weight:bold;">{label}</span>'
            if i < len(eng.sequence) - 1:
                html += f'<span style="color:{BORDER}"> → </span>'
        self.seq_label.setText(html)

    def highlight_hop(self, hop_index: int):
        eng  = self.engine
        html = ""
        for i, ch in enumerate(eng.sequence):
            color = eng.channels[ch]["color"]
            label = eng.channels[ch]["label"]
            if i == hop_index:
                html += (f'<span style="background:{color}40;color:{color};'
                         f'font-weight:bold;border:1px solid {color};'
                         f'border-radius:3px;padding:1px 3px;">{label}</span>')
            else:
                html += f'<span style="color:{color}55;font-weight:bold;">{label}</span>'
            if i < len(eng.sequence) - 1:
                html += f'<span style="color:{BORDER}"> → </span>'
        self.seq_label.setText(html)


# ─────────────────────────────────────────────────────────────────────────────
# Stats Bar
# ─────────────────────────────────────────────────────────────────────────────
class StatsBar(QWidget):
    def __init__(self, engine: FHSSEngine):
        super().__init__()
        self.engine = engine
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(10)
        self._labels = {}
        for key in ["Channels","Hop Rate","BW/Ch","Total BW","Seq Len","Modulation","SNR"]:
            frame = QFrame()
            frame.setStyleSheet(f"background:{PANEL}; border:1px solid {BORDER}; border-radius:5px;")
            fl = QVBoxLayout(frame)
            fl.setContentsMargins(8, 4, 8, 4)
            fl.setSpacing(1)
            k = QLabel(key)
            k.setStyleSheet(f"color:{MUTED}; font-size:9px;")
            v = QLabel("—")
            v.setStyleSheet(f"color:{ACCENT}; font-size:12px; font-weight:bold;")
            fl.addWidget(k)
            fl.addWidget(v)
            layout.addWidget(frame)
            self._labels[key] = v
        layout.addStretch()
        self.refresh()

    def refresh(self):
        eng = self.engine
        self._labels["Channels"].setText(str(eng.num_channels))
        self._labels["Hop Rate"].setText(f"{1000/eng.hop_interval:.0f} h/s")
        self._labels["BW/Ch"].setText(f"{eng.channel_bw:.1f} MHz")
        self._labels["Total BW"].setText(f"{eng.total_bw:.1f} MHz")
        self._labels["Seq Len"].setText(str(eng.sequence_len))
        self._labels["Modulation"].setText(eng.modulation)
        self._labels["SNR"].setText(f"{eng.snr_db:.0f} dB")


# ─────────────────────────────────────────────────────────────────────────────
# Control Panel
# ─────────────────────────────────────────────────────────────────────────────
class ControlPanel(QGroupBox):
    changed = pyqtSignal()

    def __init__(self, engine: FHSSEngine):
        super().__init__("Configuration")
        self.engine = engine
        self.setStyleSheet(f"""
            QGroupBox {{ color:{TEXT}; border:1px solid {BORDER}; border-radius:8px;
                font-size:11px; margin-top:8px; padding-top:6px; }}
            QGroupBox::title {{ subcontrol-origin:margin; left:10px; color:{ACCENT}; }}
            QLabel {{ color:{MUTED}; font-size:10px; }}
            QSpinBox, QDoubleSpinBox, QComboBox {{
                background:{BG}; color:{TEXT}; border:1px solid {BORDER};
                border-radius:4px; padding:3px 5px; font-size:10px; }}
            QComboBox QAbstractItemView {{
                background:{PANEL}; color:{TEXT}; selection-background-color:{ACCENT}40; }}
        """)
        grid = QVBoxLayout(self)
        grid.setSpacing(6)

        def row(lbl, widget):
            r = QWidget()
            h = QHBoxLayout(r)
            h.setContentsMargins(0, 0, 0, 0)
            l = QLabel(lbl)
            l.setFixedWidth(115)
            h.addWidget(l)
            h.addWidget(widget, 1)
            grid.addWidget(r)
            return widget

        self.cb_mod = row("Modulation", QComboBox())
        self.cb_mod.addItems(ModulationEngine.MODULATIONS)
        idx = self.cb_mod.findText(engine.modulation)
        if idx >= 0:
            self.cb_mod.setCurrentIndex(idx)

        self.sb_channels = row("Channels", QSpinBox())
        self.sb_channels.setRange(2, 16)
        self.sb_channels.setValue(engine.num_channels)

        self.dsb_base = row("Base Freq (MHz)", QDoubleSpinBox())
        self.dsb_base.setRange(100, 6000)
        self.dsb_base.setValue(engine.base_freq)
        self.dsb_base.setSingleStep(10)

        self.dsb_bw = row("Ch BW (MHz)", QDoubleSpinBox())
        self.dsb_bw.setRange(0.1, 20)
        self.dsb_bw.setValue(engine.channel_bw)
        self.dsb_bw.setSingleStep(0.5)

        self.sb_interval = row("Hop Interval (ms)", QSpinBox())
        self.sb_interval.setRange(1, 500)
        self.sb_interval.setValue(engine.hop_interval)

        self.sb_seqlen = row("Sequence Length", QSpinBox())
        self.sb_seqlen.setRange(4, 64)
        self.sb_seqlen.setValue(engine.sequence_len)

        self.sb_seed = row("Seed", QSpinBox())
        self.sb_seed.setRange(0, 9999)
        self.sb_seed.setValue(engine.seed)

        self.cb_pattern = row("Hop Pattern", QComboBox())
        self.cb_pattern.addItems(["Pseudo-Random", "Sequential", "Interleaved"])

        snr_row = QWidget()
        sh = QHBoxLayout(snr_row)
        sh.setContentsMargins(0, 0, 0, 0)
        snr_lbl = QLabel("SNR (dB)")
        snr_lbl.setFixedWidth(115)
        self.snr_slider = QSlider(Qt.Horizontal)
        self.snr_slider.setRange(0, 40)
        self.snr_slider.setValue(int(engine.snr_db))
        self.snr_val_lbl = QLabel(f"{engine.snr_db:.0f}")
        self.snr_val_lbl.setFixedWidth(28)
        self.snr_val_lbl.setStyleSheet(f"color:{YELLOW}; font-size:10px;")
        self.snr_slider.valueChanged.connect(lambda v: self.snr_val_lbl.setText(str(v)))
        self.snr_slider.setStyleSheet(f"""
            QSlider::groove:horizontal {{ background:{PANEL}; height:3px; border-radius:2px; }}
            QSlider::handle:horizontal {{ background:{YELLOW}; width:12px; height:12px;
                margin:-5px 0; border-radius:6px; }}
            QSlider::sub-page:horizontal {{ background:{YELLOW}; border-radius:2px; }}
        """)
        sh.addWidget(snr_lbl)
        sh.addWidget(self.snr_slider, 1)
        sh.addWidget(self.snr_val_lbl)
        grid.addWidget(snr_row)

        btn = QPushButton("Apply & Regenerate")
        btn.setStyleSheet(f"""
            QPushButton {{ background:{ACCENT}; color:#000; border:none;
                border-radius:6px; padding:6px; font-size:11px; font-weight:bold; }}
            QPushButton:hover {{ background:#33ddff; }}
        """)
        btn.clicked.connect(self._apply)
        grid.addWidget(btn)

    def _apply(self):
        self.engine.reconfigure(
            modulation   = self.cb_mod.currentText(),
            num_channels = self.sb_channels.value(),
            base_freq    = self.dsb_base.value(),
            channel_bw   = self.dsb_bw.value(),
            hop_interval = self.sb_interval.value(),
            sequence_len = self.sb_seqlen.value(),
            seed         = self.sb_seed.value(),
            pattern      = self.cb_pattern.currentText(),
            snr_db       = float(self.snr_slider.value()),
        )
        self.changed.emit()


# ─────────────────────────────────────────────────────────────────────────────
# Animation / Transport Bar
# ─────────────────────────────────────────────────────────────────────────────
class AnimBar(QWidget):
    hop_changed = pyqtSignal(int)

    def __init__(self, engine: FHSSEngine):
        super().__init__()
        self.engine   = engine
        self._hop     = 0
        self._playing = False
        self._timer   = QTimer()
        self._timer.timeout.connect(self._tick)

        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(6)

        self.btn_play  = QPushButton("▶  Play")
        self.btn_play.setFixedWidth(85)
        self.btn_reset = QPushButton("⏮  Reset")
        self.btn_reset.setFixedWidth(85)
        self.btn_play.clicked.connect(self._toggle)
        self.btn_reset.clicked.connect(self._reset)

        self.slider = QSlider(Qt.Horizontal)
        self.slider.setRange(0, engine.sequence_len - 1)
        self.slider.setValue(0)
        self.slider.valueChanged.connect(self._seek)

        self.hop_lbl = QLabel("Hop: 0 / 0")
        self.hop_lbl.setFixedWidth(95)
        self.hop_lbl.setStyleSheet(f"color:{TEXT}; font-size:10px;")

        self.speed_sb = QSpinBox()
        self.speed_sb.setRange(50, 2000)
        self.speed_sb.setValue(500)
        self.speed_sb.setSuffix(" ms")
        self.speed_sb.setFixedWidth(80)
        self.speed_sb.setStyleSheet(f"""
            QSpinBox {{ background:{PANEL}; color:{TEXT}; border:1px solid {BORDER};
                border-radius:4px; padding:2px 4px; font-size:10px; }}
        """)
        spd_lbl = QLabel("Speed:")
        spd_lbl.setStyleSheet(f"color:{MUTED}; font-size:10px;")

        for w in (self.btn_play, self.btn_reset):
            w.setStyleSheet(f"""
                QPushButton {{ background:{PANEL}; color:{TEXT}; border:1px solid {BORDER};
                    border-radius:4px; padding:4px 8px; font-size:10px; }}
                QPushButton:hover {{ background:{HOVER}; }}
            """)
        self.slider.setStyleSheet(f"""
            QSlider::groove:horizontal {{ background:{PANEL}; height:4px; border-radius:2px; }}
            QSlider::handle:horizontal {{ background:{ACCENT}; width:13px; height:13px;
                margin:-5px 0; border-radius:7px; }}
            QSlider::sub-page:horizontal {{ background:{ACCENT}40; border-radius:2px; }}
        """)

        layout.addWidget(self.btn_play)
        layout.addWidget(self.btn_reset)
        layout.addWidget(self.slider, 1)
        layout.addWidget(self.hop_lbl)
        layout.addWidget(spd_lbl)
        layout.addWidget(self.speed_sb)

    def refresh(self, engine: FHSSEngine):
        self.engine = engine
        self._hop   = 0
        self.slider.setRange(0, engine.sequence_len - 1)
        self.slider.setValue(0)
        self._update_label()

    def _toggle(self):
        self._playing = not self._playing
        if self._playing:
            self._timer.start(self.speed_sb.value())
            self.btn_play.setText("⏸  Pause")
        else:
            self._timer.stop()
            self.btn_play.setText("▶  Play")

    def _reset(self):
        self._playing = False
        self._timer.stop()
        self.btn_play.setText("▶  Play")
        self._hop = 0
        self.slider.setValue(0)
        self.hop_changed.emit(-1)

    def _tick(self):
        self._timer.setInterval(self.speed_sb.value())
        self._hop = (self._hop + 1) % self.engine.sequence_len
        self.slider.setValue(self._hop)

    def _seek(self, value: int):
        self._hop = value
        self._update_label()
        self.hop_changed.emit(value)

    def _update_label(self):
        self.hop_lbl.setText(f"Hop: {self._hop+1} / {self.engine.sequence_len}")


# ─────────────────────────────────────────────────────────────────────────────
# Main Window
# ─────────────────────────────────────────────────────────────────────────────
class FHSSWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("FHSS Simulation v3  —  FFT · Waterfall · Modulation · Demod Console")
        self.resize(1500, 920)
        self.engine = FHSSEngine()
        self._build_ui()
        self._apply_global_style()

    def _apply_global_style(self):
        self.setStyleSheet(f"""
            QMainWindow, QWidget {{ background:{BG}; color:{TEXT}; }}
            QTabWidget::pane {{ border:1px solid {BORDER}; background:{PANEL}; }}
            QTabBar::tab {{ background:{BG}; color:{MUTED}; padding:6px 16px;
                border:1px solid {BORDER}; border-bottom:none; font-size:11px; }}
            QTabBar::tab:selected {{ background:{PANEL}; color:{TEXT}; border-top:2px solid {ACCENT}; }}
            QSplitter::handle {{ background:{BORDER}; }}
            QScrollBar:vertical {{ background:{BG}; width:7px; }}
            QScrollBar::handle:vertical {{ background:{BORDER}; border-radius:3px; }}
            QCheckBox {{ color:{MUTED}; font-size:10px; }}
            QCheckBox::indicator {{ width:12px; height:12px; border:1px solid {BORDER};
                border-radius:2px; background:{BG}; }}
            QCheckBox::indicator:checked {{ background:{ACCENT}; border-color:{ACCENT}; }}
        """)

    def _build_ui(self):
        central = QWidget()
        self.setCentralWidget(central)
        root = QVBoxLayout(central)
        root.setContentsMargins(10, 8, 10, 8)
        root.setSpacing(8)

        hdr = QLabel("⟁  FHSS Simulation  ·  FFT + Waterfall + Modulation + Demod Console")
        hdr.setStyleSheet(f"""
            color:{ACCENT}; font-size:16px; font-weight:700; font-family:'Courier New';
            letter-spacing:1.5px; border-bottom:1px solid {BORDER}; padding-bottom:5px;
        """)
        root.addWidget(hdr)

        self.stats = StatsBar(self.engine)
        root.addWidget(self.stats)

        # Main horizontal splitter: left (viz tabs) | right (config+table)
        main_split = QSplitter(Qt.Horizontal)
        main_split.setHandleWidth(2)

        # ── Left: vertical splitter — viz on top, console below ───────────────
        left_vsplit = QSplitter(Qt.Vertical)
        left_vsplit.setHandleWidth(3)

        # Upper: tabs (FFT/Waterfall and Hop Map)
        self.tabs = QTabWidget()

        tab_spec = QWidget()
        tv1 = QVBoxLayout(tab_spec)
        tv1.setContentsMargins(4, 4, 4, 4)
        tv1.setSpacing(6)
        self.spec_canvas = SpectrumCanvas(self.engine)
        # Connect IQ signal to demod console
        self.spec_canvas.iq_generated.connect(self._on_iq_generated)
        tv1.addWidget(self.spec_canvas, 1)
        self.tabs.addTab(tab_spec, "📡  FFT + Waterfall")

        tab_hop = QWidget()
        tv2 = QVBoxLayout(tab_hop)
        tv2.setContentsMargins(4, 4, 4, 4)
        tv2.setSpacing(6)
        self.hop_canvas = HopMapCanvas(self.engine)
        tv2.addWidget(self.hop_canvas, 1)
        self.seq_widget = SequenceWidget(self.engine)
        tv2.addWidget(self.seq_widget)
        self.tabs.addTab(tab_hop, "📶  Hop Map")

        # Anim bar below tabs, above the console
        upper_w = QWidget()
        uv = QVBoxLayout(upper_w)
        uv.setContentsMargins(0, 0, 0, 0)
        uv.setSpacing(4)
        uv.addWidget(self.tabs, 1)
        self.anim_bar = AnimBar(self.engine)
        self.anim_bar.hop_changed.connect(self._on_hop)
        uv.addWidget(self.anim_bar)

        left_vsplit.addWidget(upper_w)

        # Lower: Demodulation Console
        self.demod_console = DemodConsole(self.engine)
        left_vsplit.addWidget(self.demod_console)

        left_vsplit.setSizes([560, 280])
        main_split.addWidget(left_vsplit)

        # ── Right: config + channel table ─────────────────────────────────────
        right_w = QWidget()
        rv = QVBoxLayout(right_w)
        rv.setContentsMargins(6, 0, 0, 0)
        rv.setSpacing(8)

        self.ctrl = ControlPanel(self.engine)
        self.ctrl.changed.connect(self._on_config_changed)
        rv.addWidget(self.ctrl)

        ch_lbl = QLabel("Channel List")
        ch_lbl.setStyleSheet(f"color:{MUTED}; font-size:10px; font-weight:600;")
        rv.addWidget(ch_lbl)

        self.table = ChannelTable(self.engine)
        rv.addWidget(self.table)

        main_split.addWidget(right_w)
        main_split.setSizes([1020, 380])
        root.addWidget(main_split, 1)

    # ── Slots ─────────────────────────────────────────────────────────────────
    def _on_config_changed(self):
        self.spec_canvas.rebuild()
        self.hop_canvas._draw_static()
        self.stats.refresh()
        self.table.refresh()
        self.seq_widget.refresh()
        self.anim_bar.refresh(self.engine)
        self.demod_console.engine = self.engine

    def _on_hop(self, hop_index: int):
        self.spec_canvas.update_hop(hop_index)
        self.hop_canvas.highlight_hop(hop_index)
        if hop_index >= 0:
            ch_idx = self.engine.sequence[hop_index]
            self.table.highlight_channel(ch_idx)
            self.seq_widget.highlight_hop(hop_index)
            self.anim_bar._update_label()
        else:
            self.table.clearSelection()
            self.seq_widget.refresh()

    def _on_iq_generated(self, hop_index: int, ch_index: int, iq_samples: object):
        """Relay IQ samples from spectrum canvas to demod console."""
        self.demod_console.log_hop(hop_index, ch_index, iq_samples)


# ─────────────────────────────────────────────────────────────────────────────
# Entry Point
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    app = QApplication(sys.argv)
    app.setStyle("Fusion")
    palette = QPalette()
    palette.setColor(QPalette.Window,        QColor(BG))
    palette.setColor(QPalette.WindowText,    QColor(TEXT))
    palette.setColor(QPalette.Base,          QColor(PANEL))
    palette.setColor(QPalette.AlternateBase, QColor(BG))
    palette.setColor(QPalette.Text,          QColor(TEXT))
    palette.setColor(QPalette.Button,        QColor(PANEL))
    palette.setColor(QPalette.ButtonText,    QColor(TEXT))
    app.setPalette(palette)
    win = FHSSWindow()
    win.show()
    sys.exit(app.exec_())